const articles = [
    {
        id: '1',
        name: 'iPhone 12 Pro',
        storage: '64GB',
        price:'250.000',
        color: 'graphite',
        category: 'ip1',
        stock: 5,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'El iPhone 12 tiene una espectacular pantalla Super Retina XDR de 6.1 pulgadas (1). Un frente de Ceramic Shield, cuatro veces más resistente a las caídas (2). Modo Noche en todas las cámaras, para que puedas tomar fotos increíbles con poca luz. Grabación, edición y reproducción de video en Dolby Vision con calidad cinematográfica. Y el potente chip A14 Bionic.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_834378-MLA46078159682_052021-F.webp',
    },
    {
        id: '2',
        name: 'iPhone 12 Pro',
        storage: '128GB',
        price:'439.990',
        color: 'white',
        category: 'ip1',
        stock: 3,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'El iPhone 12 tiene una espectacular pantalla Super Retina XDR de 6.1 pulgadas (1). Un frente de Ceramic Shield, cuatro veces más resistente a las caídas (2). Modo Noche en todas las cámaras, para que puedas tomar fotos increíbles con poca luz. Grabación, edición y reproducción de video en Dolby Vision con calidad cinematográfica. Y el potente chip A14 Bionic.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_930111-MLA46079922176_052021-F.webp',
    },
    {
        id: '3',
        name: 'iPhone 12 Pro',
        storage: '256GB',
        price:'439.990',
        color: 'gold',
        category: 'ip1',
        stock: 2,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'El iPhone 12 tiene una espectacular pantalla Super Retina XDR de 6.1 pulgadas (1). Un frente de Ceramic Shield, cuatro veces más resistente a las caídas (2). Modo Noche en todas las cámaras, para que puedas tomar fotos increíbles con poca luz. Grabación, edición y reproducción de video en Dolby Vision con calidad cinematográfica. Y el potente chip A14 Bionic.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_695472-MLA46080736565_052021-F.webp',
    },
    {
        id: '4',
        name: 'iPhone 13 mini',
        storage: '256GB',
        price: '280.000',
        color: 'blue midnight',
        category: 'ip1',
        stock: 2,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 13. El sistema de dos cámaras más avanzado en un iPhone. El superrápido chip A15 Bionic. Un gran salto en duración de batería. Un diseño resistente. Y una pantalla Super Retina XDR más brillante.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_881936-MLA47782477423_102021-F.webp',
    },
    {
        id: '5',
        name: 'iPhone 13 mini',
        storage: '256GB',
        price: '280.000',
        color: 'red',
        category: 'ip1',
        stock: 3,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 13. El sistema de dos cámaras más avanzado en un iPhone. El superrápido chip A15 Bionic. Un gran salto en duración de batería. Un diseño resistente. Y una pantalla Super Retina XDR más brillante.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_813854-MLA47782406057_102021-F.webp',
    },
    {
        id: '6',
        name: 'iPhone 13',
        storage: '256GB',
        price: '357.999',
        color: 'blue midnight',
        category: 'ip1',
        stock: 4,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 13. El sistema de dos cámaras más avanzado en un iPhone. El superrápido chip A15 Bionic. Un gran salto en duración de batería. Un diseño resistente. Y una pantalla Super Retina XDR más brillante.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_619667-MLA47781882790_102021-F.webp',
    },
    {
        id: '7',
        name: 'iPhone 13',
        storage: '256GB',
        price: '357.999',
        color: 'estelar white',
        category: 'ip1',
        stock: 6,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 13. El sistema de dos cámaras más avanzado en un iPhone. El superrápido chip A15 Bionic. Un gran salto en duración de batería. Un diseño resistente. Y una pantalla Super Retina XDR más brillante.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_736168-MLA47781742030_102021-F.webp',
    },
    {
        id: '8',
        name: 'iPhone 13',
        storage: '256GB',
        price: '357.999',
        color: 'pink',
        category: 'ip1',
        stock: 5,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 13. El sistema de dos cámaras más avanzado en un iPhone. El superrápido chip A15 Bionic. Un gran salto en duración de batería. Un diseño resistente. Y una pantalla Super Retina XDR más brillante.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_654080-MLA47781882564_102021-F.webp',
    },
    {
        id: '9',
        name: 'iPhone 13 Pro Max',
        storage: '256GB',
        price: '514.655',
        color: 'graphite',
        category: 'ip1',
        stock: 5,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 13 Pro Max. El mayor avance en el sistema de cámaras Pro hasta ahora. Pantalla Super Retina XDR con ProMotion que brinda una respuesta más rápida y fluida. Chip A15 Bionic para un rendimiento fuera de serie. Diseño resistente y la mayor duración de batería jamás vista en un iPhone.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_799027-MLA47776845273_102021-F.webp',
    },
    {
        id: '10',
        name: 'iPhone 13 Pro Max',
        storage: '256GB',
        price: '514.655',
        color: 'gold',
        category: 'ip1',
        stock: 8,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 13 Pro Max. El mayor avance en el sistema de cámaras Pro hasta ahora. Pantalla Super Retina XDR con ProMotion que brinda una respuesta más rápida y fluida. Chip A15 Bionic para un rendimiento fuera de serie. Diseño resistente y la mayor duración de batería jamás vista en un iPhone.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_619217-MLA47776936253_102021-F.webp',
    },
    {
        id: '11',
        name: 'iPhone 13 Pro Max',
        storage: '256GB',
        price: '514.655',
        color: 'blue',
        category: 'ip1',
        stock: 4,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 13 Pro Max. El mayor avance en el sistema de cámaras Pro hasta ahora. Pantalla Super Retina XDR con ProMotion que brinda una respuesta más rápida y fluida. Chip A15 Bionic para un rendimiento fuera de serie. Diseño resistente y la mayor duración de batería jamás vista en un iPhone.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_768980-MLA47777512590_102021-F.webp',
    },
    {
        id: '12',
        name: 'iPhone 14 Pro Max',
        storage: '256GB',
        price: '859.990',
        color: 'graphite',
        category: 'ip1',
        stock: 1,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'iPhone 14 Pro Max. El mayor avance en el sistema de cámaras Pro hasta ahora. Pantalla Super Retina XDR con ProMotion que brinda una respuesta más rápida y fluida. Chip A15 Bionic para un rendimiento fuera de serie. Diseño resistente y la mayor duración de batería jamás vista en un iPhone.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_619797-MLA51592858832_092022-O.webp',
    },
    {
        id: '13',
        name: 'iPad (9a generacion)',
        storage: '128GB',
        price: '84.080',
        color: 'plate',
        category: 'ipad2',
        stock: 11,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'Lleno de potencia, muy fácil de usar y versátil. El nuevo iPad viene con una espectacular pantalla Retina de 10.2 pulgadas, el potente chip A13 Bionic y una cámara frontal ultra gran angular con Encuadre Centrado. Además, es compatible con el Apple Pencil y el Smart Keyboard. Con el iPad, harás de todo como si nada. Y por menos de lo que imaginas.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_711191-MLA47871333065_102021-F.webp',
    },
    {
        id: '14',
        name: 'iPad (4ta generacion) WI-FI',
        storage: '128GB',
        price: '135.000',
        color: 'grey',
        category: 'ipad2',
        stock: 5,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'El nuevo iPad Air es más versátil que nunca. La increíble pantalla Liquid Retina de 10,9 pulgadas con amplia gama de colores hace que las fotos, videos y juegos se vean con un nivel de detalle superior(1). El chip A14 Bionic con Neural Engine tiene potencia de sobra y capacidades avanzadas de aprendizaje automático para que puedas editar videos 4K, crear presentaciones inolvidables y diseñar modelos 3D con mucha facilidad. Además, el iPad Air ahora es compatible con el Magic Keyboard y el Apple Pencil (segunda generación)(2), y viene con TouchID: un sistema de autenticación rápido, sencillo y seguro. También incluye una cámara trasera de 12MP y una cámara FaceTime HD de 7 MP, un puerto USB-C para cargar el iPad Air y conectar accesorios y batería para todo el día(3). El iPadAir pone en tus manos toda la potencia que necesitas para dar vida a tus ideas.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_988198-MLA46962206200_082021-F.webp',
    },
    {
        id: '15',
        name: 'iPad mini WI-FI',
        storage: '128GB',
        price: '121.892',
        color: 'estelar white',
        category: 'ipad2',
        stock: 2,
        seller: 'iStore',
        ubication: 'Ciudad Autonoma de Buenos Aires',
        description: 'El nuevo iPad mini viene con una pantalla Liquid Retina de 8.3 pulgadas con diseño de borde a borde (1) y el poderoso chip A15 Bionic con Neural Engine. Además, tiene una cámara frontal ultra gran angular de 12 MP con Encuadre Centrado y conectividad USB-C. Toma apuntes, haz anotaciones en documentos y dales vida a tus mejores ideas con el Apple Pencil (segunda generación), que se adhiere magnéticamente al iPad mini y se carga de forma inalámbrica.',
        image: 'https://http2.mlstatic.com/D_NQ_NP_2X_834625-MLA48035066227_102021-F.webp',
    },

]

export default articles;